spring:
  datasource:
    url: jdbc:mysql://localhost:3306/scmdb
    username: omsuser
    password: omsuser

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL57Dialect
        format_sql: true
